INSERT INTO public.ad_roles
(id_rol, nombre)
VALUES
(nextval('ad_roles_id_rol_seq'), 'ROL_ADMINISTRADOR'),
(nextval('ad_roles_id_rol_seq'), 'ROL_VENDEDOR'),
(nextval('ad_roles_id_rol_seq'), 'ROL_SUPERVISOR'),
(nextval('ad_roles_id_rol_seq'), 'ROL_GERENTE'),
(nextval('ad_roles_id_rol_seq'), 'ROL_CONTADOR'),
(nextval('ad_roles_id_rol_seq'), 'ROL_AUXILIAR_CONTABLE'),
(nextval('ad_roles_id_rol_seq'), 'ROL_PAGADOR'),
(nextval('ad_roles_id_rol_seq'), 'ROL_COBRADOR');


INSERT INTO public.ad_grupos
(id_grupo, nombre)
VALUES
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_CONTABILIDAD_OPERATIVO'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_CONTABILIDAD_CIERRE'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_CONTABILIDAD_SUPERVISION'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_VENTAS_OPERATIVO'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_VENTAS_SUPERVISOR'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_VENTAS_REPORTES'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_COMPRAS_OPERATIVO'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_COMPRAS_SUPERVISOR'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_COMPRAS_REPORTES'),
(nextval('ad_grupos_id_grupo_seq'), 'GRUPO_DE_TODOS_LOS_PERMISOS');



INSERT INTO public.ad_permisos
(id_permiso, descripcion, permiso)
VALUES
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS CREAR','VT_FC_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS MODIFCAR','VT_FC_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS ANULAR','VT_FC_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS ELIMINAR','VT_FC_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS VER','VT_FC_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS EXPORTAR','VT_FC_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS IMPORTAR EXCEL','VT_FC_IMEX'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS CREDITO CREAR','VT_NC_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS CREDITO MODIFCAR','VT_NC_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS CREDITO ANULAR','VT_NC_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS CREDITO ELIMINAR','VT_NC_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS CREDITO VER','VT_NC_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS DEBITO CREAR','VT_ND_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS DEBITO MODIFCAR','VT_ND_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS DEBITO ANULAR','VT_ND_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS DEBITO ELIMINAR','VT_ND_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	NOTAS DEBITO VER','VT_ND_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	REEMBOLSOS CREAR','VT_RB_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	REEMBOLSOS MODIFCAR','VT_RB_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	REEMBOLSOS ANULAR','VT_RB_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	REEMBOLSOS ELIMINAR','VT_RB_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	REEMBOLSOS VER','VT_RB_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS REEMBOLSOS IMPORTAR XML','VT_RB_IMXML'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	FACTURAS EXPORTAR','VT_RB_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION CREAR','VT_GR_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION MODIFCAR','VT_GR_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION ANULAR','VT_GR_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION ELIMINAR','VT_GR_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION VER','VT_GR_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	GUIAS REMISION EXPORTAR','VT_GR_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	PEDIDOS	CREAR','VT_PD_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	PEDIDOS	MODIFCAR','VT_PD_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	PEDIDOS	ELIMINAR','VT_PD_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	PEDIDOS	VER','VT_PD_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	PEDIDOS	EXPORTAR','VT_PD_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	RETENCIONES	CREAR','VT_RT_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	RETENCIONES	MODIFCAR','VT_RT_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	RETENCIONES	ELIMINAR','VT_RT_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	RETENCIONES	VER','VT_RT_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	RETENCIONES	EXPORTAR','VT_RT_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS CREAR','CP_CP_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS MODIFCAR','CP_CP_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS ANULAR','CP_CP_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS ELIMINAR','CP_CP_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS VER','CP_CP_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS EXPORTAR','CP_CP_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS IMPUESTOS CREAR','CP_CI_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS IMPUESTOS MODIFCAR','CP_CI_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS IMPUESTOS ELIMINAR','CP_CI_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS IMPUESTOS VER','CP_CI_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS COMPRAS IMPUESTOS EXPORTAR','CP_CI_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES CREAR','CP_RT_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES MODIFCAR','CP_RT_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES ANULAR','CP_RT_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES ELIMINAR','CP_RT_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES VER','CP_RT_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS RETENCIONES EXPORTAR','CP_RT_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS CREAR','CP_OC_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS MODIFCAR','CP_OC_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS ANULAR','CP_OC_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS ELIMINAR','CP_OC_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS VER','CP_OC_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'COMPRAS ORDEN COMPRAS EXPORTAR','CP_OC_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL ITEMS CREAR','GE_IT_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL ITEMS MODIFCAR','GE_IT_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL ITEMS ELIMINAR','GE_IT_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL ITEMS VER','GE_IT_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL TERCERO CREAR','GE_TE_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL TERCERO MODIFCAR','GE_TE_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL TERCERO ELIMINAR','GE_TE_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'GENERAL TERCERO VER','GE_TE_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS CREAR','CN_AS_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS MODIFCAR','CN_AS_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS ELIMINAR','CN_AS_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS VER','CN_AS_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS BALANCES','CN_AS_BL'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD ASIENTOS REPORTES','CN_AS_RP'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD CENTRO COSTOS CREAR','CN_CC_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD CENTRO COSTOS MODIFCAR','CN_CC_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD CENTRO COSTOS ELIMINAR','CN_CC_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'CONTABILIDAD CENTRO COSTOS VER','CN_CC_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	CLIENTES GRUPOS	CREAR','VT_CG_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	CLIENTES GRUPOS	MODIFCAR','VT_CG_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	CLIENTES GRUPOS	ELIMINAR','VT_CG_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS CLIENTES GRUPOS	VER','VT_CG_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	COTIZACIONES CREAR','VT_CO_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'VENTAS	COTIZACIONES MODIFCAR','VT_CO_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS COTIZACIONES ELIMINAR','VT_CO_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS COTIZACIONES VER','VT_CO_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS COTIZACIONES EXPORTAR','VT_CO_EX'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS VENDEDORES CREAR','VT_VE_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS VENDEDORES MODIFCAR','VT_VE_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS VENDEDORES ELIMINAR','VT_VE_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS VENDEDORES VER','VT_VE_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS ZONAS CREAR','VT_ZO_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS ZONAS MODIFCAR','VT_ZO_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS ZONAS ELIMINAR','VT_ZO_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS ZONAS VER','VT_ZO_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES GRUPOS CREAR','CP_PG_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES GRUPOS MODIFCAR','CP_PG_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES GRUPOS ELIMINAR','CP_PG_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES GRUPOS VER','CP_PG_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONTABILIDAD PLAN CUENTAS CREAR','CN_PC_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONTABILIDAD PLAN CUENTAS MODIFCAR','CN_PC_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'CONTABILIDAD PLAN CUENTAS ELIMINAR','CN_PC_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'CONTABILIDAD PLAN CUENTAS VER','CN_PC_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS CLIENTES PARAMETROS CREAR','VT_CP_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS CLIENTES PARAMETROS MODIFCAR','VT_CP_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS CLIENTES PARAMETROS ELIMINAR','VT_CP_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'VENTAS CLIENTES PARAMETROS VER','VT_CP_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES PARAMETROS CREAR','CP_PP_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES PARAMETROS MODIFCAR','CP_PP_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES PARAMETROS ELIMINAR','CP_PP_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'COMPRAS PROVEEDORES PARAMETROS VER','CP_PP_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL BODEGAS CREAR','GE_BO_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL BODEGAS MODIFCAR','GE_BO_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL BODEGAS ELIMINAR','GE_BO_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL BODEGAS VER','GE_BO_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL CATEGORIAS CREAR','GE_CA_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL CATEGORIAS MODIFCAR','GE_CA_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL CATEGORIAS ELIMINAR','GE_CA_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL CATEGORIAS VER','GE_CA_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL ITEMS GRUPOS CREAR','GE_IG_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL ITEMS GRUPOS MODIFCAR','GE_IG_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL ITEMS GRUPOS ELIMINAR','GE_IG_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL ITEMS GRUPOS VER','GE_IG_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MARCAS CREAR','GE_MA_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MARCAS MODIFCAR','GE_MA_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MARCAS ELIMINAR','GE_MA_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MARCAS VER','GE_MA_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MEDIDAS CREAR','GE_ME_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MEDIDAS MODIFCAR','GE_ME_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MEDIDAS ELIMINAR','GE_ME_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'GENERAL MEDIDAS VER','GE_ME_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONTABILIDAD PLAN CUENTAS IMPORTAR EXCEL','CN_PC_IMEX'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES DATAS CREAR','CF_DT_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES DATAS MODIFICAR','CF_DT_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES DATAS VER','CF_DT_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES DATAS USUARIO CREAR','CF_DTU_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES DATAS USUARIO VER','CF_DTU_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES LISTA NEGRA VER','CF_LN_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CONFIGURACIONES LISTA NEGRA ELIMINAR','CF_LN_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  USUARIOS CREAR','US_US_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  USUARIOS MODIFICAR','US_US_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  USUARIOS VER','US_US_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  ROLES CREAR','US_RL_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  ROLES MODIFICAR','US_RL_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  ROLES VER','US_RL_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  ROLES ELIMINAR','US_RL_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  GRUPOS CREAR','US_GR_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  GRUPOS MODIFICAR','US_GR_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  GRUPOS VER','US_GR_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  GRUPOS ELIMINAR','US_GR_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  PERMISOS CREAR','US_PE_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  PERMISOS MODIFICAR','US_PE_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  PERMISOS VER','US_PE_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'USUARIOS  PERMISOS ELIMINAR','US_PE_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION EMPRESAS CREAR','AD_EM_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION EMPRESAS MODIFICAR','AD_EM_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION EMPRESAS VER','AD_EM_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SERIES CREAR','AD_SE_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SERIES MODIFICAR','AD_SE_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SERIES VER','AD_SE_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SERIES ELIMINAR','AD_SE_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION DOCUMENTOS VER','AD_DO_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SUCURSALES CREAR','AD_SU_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SUCURSALES MODIFICAR','AD_SU_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SUCURSALES VER','AD_SU_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'ADMINISTRACION SUCURSALES ELIMINAR','AD_SU_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES CONFIGURACIONES CREAR','CR_CC_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES CONFIGURACIONES MODIFCAR','CR_CC_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES CONFIGURACIONES ELIMINAR','CR_CC_EL'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES CONFIGURACIONES VER','CR_CC_VR'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES TICKETS CREAR','CR_CT_CR'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES TICKETS MODIFCAR','CR_CT_MO'),
(nextval('ad_permisos_id_permiso_seq'),   'CRM CLIENTES TICKETS VER','CR_CT_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES CREAR','LQ_LQ_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES MODIFCAR','LQ_LQ_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES ANULAR','LQ_LQ_AN'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES ELIMINAR','LQ_LQ_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES VER','LQ_LQ_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACIONES EXPORTAR','LQ_LQ_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS CREAR','LQ_LQR_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS MODIFCAR','LQ_LQR_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS ELIMINAR','LQ_LQR_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS VER','LQ_LQR_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS EXPORTAR','LQ_LQR_EX'),
(nextval('ad_permisos_id_permiso_seq'),  'LIQUIDACIONES LIQUIDACION REEMBOLSOS IMPORTAR XML','LQ_LQR_IMXML'),
(nextval('ad_permisos_id_permiso_seq'),  'IMPUESTOS	FORMULARIO 103 VER','IM_F103_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'IMPUESTOS	FORMULARIO 104 VER','IM_F104_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'IMPUESTOS	FORMULARIO 107 VER','IM_F107_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'IMPUESTOS	TALON RESUMEN VER','IM_TR_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'IMPUESTOS ATS VER','IM_AT_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR COBRAR CREAR','CX_XC_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR COBRAR MODIFICAR','CX_XC_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR COBRAR VER','CX_XC_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR COBRAR ELIMINAR','CX_XC_EL'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR PAGAR	CREAR','CX_XP_CR'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR PAGAR	MODIFICAR','CX_XP_MO'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR PAGAR	VER','CX_XP_VR'),
(nextval('ad_permisos_id_permiso_seq'),  'CUENTAS POR PAGAR	ELIMINAR','CX_XP_EL');


INSERT INTO public.ad_grupos_permisos (id_grupo, id_permiso)
SELECT
    (SELECT g.id_grupo
     FROM public.ad_grupos g
     WHERE g.nombre = 'GRUPO_DE_TODOS_LOS_PERMISOS'),
    p.id_permiso
FROM public.ad_permisos p;

INSERT INTO public.ad_rol_grupos (id_rol, id_grupo)
SELECT
    r.id_rol,
    g.id_grupo
FROM public.ad_roles r
JOIN public.ad_grupos g
    ON g.nombre = 'GRUPO_DE_TODOS_LOS_PERMISOS'
WHERE r.nombre = 'ROL_ADMINISTRADOR';

INSERT INTO public.ad_usuarios_roles (id_usuario, id_rol)
SELECT
    1,
    r.id_rol
FROM public.ad_roles r
WHERE r.nombre = 'ROL_ADMINISTRADOR';


UPDATE public.ad_permisos
SET deleted=false;


UPDATE public.ad_grupos
SET  deleted=false;


UPDATE public.ad_roles
SET  deleted=false;