INSERT INTO public.tb_retenciones_codigos
(id, deleted, codigo, codigo_retencion, nombre_retencion, porcentaje)
VALUES
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '303', 'Honorarios profesionales y demás pagos por servicios relacionados con el título profesional', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '303A', 'Servicios profesionales prestados por sociedades residentes', 5),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304', 'Servicios predomina el intelecto no relacionados con el título profesional', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304A', 'Comisiones y demás pagos por servicios predomina intelecto no relacionados con el título profesional', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304B', 'Pagos a notarios y registradores de la propiedad y mercantil por sus actividades ejercidas como tales', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304C', 'Pagos a deportistas, entrenadores, árbitros, miembros del cuerpo técnico por sus actividades ejercidas como tales', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304D', 'Pagos a artistas por sus actividades ejercidas como tales', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '304E', 'Honorarios y demás pagos por servicios de docencia', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '307', 'Servicios predomina la mano de obra', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '308', 'Utilización o aprovechamiento de la imagen o renombre (personas naturales, sociedades," influencers")', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '309', 'Servicios prestados por medios de comunicación y agencias de publicidad', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '310', 'Servicio de transporte privado de pasajeros o transporte público o privado de carga', 1),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '311', 'Pagos a través de liquidación de compra (nivel cultural o rusticidad)', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '312', 'Transferencia de bienes muebles de naturaleza corporal', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '312A', 'COMPRAS AL PRODUCTOR: de bienes de origen bioacuático, forestal y los descritos  el art.27.1 de LRTI ', 1),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '312C', 'COMPRAS AL COMERCIALIZADOR: de bienes de origen bioacuático, forestal y los descritos  el art.27.1 de LRTI', 1.75),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '314A', 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a personas naturales', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '314B', 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo  al Código INGENIOS (COESCCI) – pago a personas naturales', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '314C', 'Regalías por concepto de franquicias de acuerdo al Código INGENIOS (COESCCI) - pago a sociades', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '314D', 'Cánones, derechos de autor,  marcas, patentes y similares de acuerdo  al Código INGENIOS (COESCCI)  ', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '319', 'Cuotas de arrendamiento mercantil (prestado por sociedades), inclusive la de opción de compra', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '320', 'Arrendamiento bienes inmuebles', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '322', 'Seguros y reaseguros (primas y cesiones)', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323', 'Rendimientos financieros pagados a naturales y sociedades  (No a IFIs)', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323A', 'Rendimientos financieros depósitos Cta. Corriente', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323B1', 'Rendimientos financieros  depósitos Cta. Ahorros Sociedades', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323E', 'Rendimientos financieros depósito a plazo fijo  gravados', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323E2', 'Rendimientos financieros depósito a plazo fijo exentos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323F', 'Rendimientos financieros operaciones de reporto - repos', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323G', 'Inversiones (captaciones) rendimientos distintos de aquellos pagados a IFIs', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323H', 'Rendimientos financieros  obligaciones', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323I', 'Rendimientos financieros  bonos convertible en acciones', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323 M', 'Rendimientos financieros : Inversiones en títulos valores en renta fija gravados ', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323 N', 'Rendimientos financieros  Inversiones en títulos valores en renta fija exentos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323 O', 'Intereses y demás rendimientos financieros pagados a bancos y otras entidades sometidas al control de la Superintendencia de Bancos y de la Economía Popular y Solidaria', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323 P', ' Intereses pagados por entidades del sector público a favor de sujetos pasivos', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323Q', 'Otros intereses y rendimientos financieros gravados ', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323R', 'Otros intereses y rendimientos financieros exentos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323S', 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras personas naturales y sociedades', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323T', 'Rendimientos financieros originados en la deuda pública ecuatoriana', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '323U', 'Rendimientos financieros originados en títulos valores de obligaciones de 360 días o más para el financiamiento de proyectos públicos en asociación público-privada', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '324A', ' Intereses en operaciones de crédito entre instituciones del sistema financiero y entidades economía popular y solidaria. ', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '324B', 'Inversiones entre instituciones del sistema financiero y entidades economía popular y solidaria', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '324C', 'Pagos y créditos en cuenta efectuados por el BCE y los depósitos centralizados de valores, en calidad de intermediarios, a instituciones del sistema financiero por cuenta de otras instituciones del sistema financiero', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '325', 'Anticipo dividendos', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '325A', 'Préstamos accionistas, beneficiarios o partícipes residentes o establecidos en el Ecuador', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '3250', 'Dividendos exentos (por no llegar a franja exenta o beneficio de otras leyes)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '326', 'Dividendos distribuidos que correspondan al impuesto a la renta único establecido en el art. 27 de la LRTI', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '327', 'Dividendos distribuidos a personas naturales residentes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '328', 'Dividendos distribuidos a sociedades residentes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '329', 'Dividendos distribuidos a fideicomisos residentes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '331', 'Dividendos en acciones (capitalización de utilidades)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332', 'Otras compras de bienes y servicios no sujetas a retención (incluye régimen RIMPE - Negocios Populares, para este caso aplica con cualquier forma de pago inclusive los pagos que deban realizar las tarjetas de crédito/débito)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332B', 'Compra de bienes inmuebles', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332C', 'Transporte público de pasajeros', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332D', 'Pagos en el país por transporte de pasajeros o transporte internacional de carga, a compañías nacionales o extranjeras de aviación o marítimas', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332E', 'Valores entregados por las cooperativas de transporte a sus socios', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332F', 'Compraventa de divisas distintas al dólar de los Estados Unidos de América', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332G', 'Pagos con tarjeta de crédito ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332H', 'Pago al exterior tarjeta de crédito reportada por la Emisora de tarjeta de crédito, solo recap', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '332I', 'Pago a través de convenio de debito (Clientes IFI`s)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '333', 'Ganancia en la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, que se coticen en bolsa de valores del Ecuador', 10),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '334', 'Contraprestación producida por la enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades, no cotizados en bolsa de valores del Ecuador', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '335', 'Loterías, rifas, pronósticos deportivos, apuestas y similares ', 15),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '336', 'Venta de combustibles a comercializadoras', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '337', 'Venta de combustibles a distribuidores', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '338', 'Producción y venta local de banano producido o no por el mismo sujeto pasivo', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '340', 'Impuesto único a la exportación de banano', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '343', 'Otras retenciones aplicables el 1% (incluye régimen RIMPE - Emprendedores, para este caso aplica con cualquier forma de pago inclusive los pagos que deban realizar las tarjetas de crédito/débito)', 1),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '343A', 'Energía eléctrica', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '343B', 'Actividades de construcción de obra material inmueble, urbanización, lotización o actividades similares', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '343C', 'Recepción de botellas plásticas no retornables de PET', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '3440', 'Otras retenciones aplicables el 3% ', 3),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '344A', 'Pago local tarjeta de crédito /débito reportada por la Emisora de tarjeta de crédito / entidades del sistema financiero/sistemas auxiliares de pago', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '344B', 'Adquisición de sustancias minerales dentro del territorio nacional', 2),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '346', 'Otras retenciones aplicables a otros porcentajes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '346A', 'Otras ganancias de capital distintas de enajenación de derechos representativos de capital ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '346B', 'Donaciones en dinero -Impuesto a las donaciones ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '346C', 'Retención a cargo del propio sujeto pasivo por la producción y/o comercialización de minerales y otros bienes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '346D', 'Retención a cargo del propio sujeto pasivo por la comercialización de productos forestales', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '350', 'Otras autorretenciones (inciso 1 y 2 Art.92.1 RLRTI)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '3480', 'Impuesto a la renta único sobre los ingresos percibidos por los operadores de pronósticos deportivos', 15),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '3481', 'Autorretenciones Sociedades Grandes Contribuyentes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '3482', 'Comisiones  a sociedades, nacionales o extranjeras residentes y establecimientos permanentes domiciliados en el país', 5),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '500', 'Pago a no residentes - Rentas Inmobiliarias', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '501', 'Pago a no residentes - Beneficios/Servicios  Empresariales', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '501A', 'Pago a no residentes - Servicios técnicos, administrativos o de consultoría y regalías', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '503', 'Pago a no residentes- Navegación Marítima y/o aérea', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504', 'Pago a no residentes- Dividendos distribuidos a personas naturales (domiciliados o no en paraíso fiscal) o a sociedades sin beneficiario efectivo persona natural residente en Ecuador', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504A', 'Dividendos a sociedades con beneficiario efectivo persona natural residente en el Ecuador', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504B', 'Dividendos a no residentes incumpliendo el deber de informar la composición societaria', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504C', 'Dividendos a residentes o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504D', 'Dividendos a fideicomisos o establecidos en paraísos fiscales o regímenes de menor imposición (con beneficiario Persona Natural residente en Ecuador)', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504E', 'Pago a no residentes - Anticipo dividendos (no domiciliada en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504F', 'Pago a no residentes - Anticipo dividendos (domiciliadas en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504G', 'Pago a no residentes - Préstamos accionistas, beneficiarios o partícipes (no domiciliadas en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504H', 'Pago a no residentes - Préstamos accionistas, beneficiarios o partícipes (domiciliadas en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504I', 'Pago a no residentes - Préstamos no comerciales a partes relacionadas  (no domiciliadas en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '504J', 'Pago a no residentes - Préstamos no comerciales a partes relacionadas  (domiciliadas en paraísos fiscales o regímenes de menor imposición)', 25),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505', 'Pago a no residentes - Rendimientos financieros', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505A', 'Pago a no residentes – Intereses de créditos de Instituciones Financieras del exterior', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505B', 'Pago a no residentes – Intereses de créditos de gobierno a gobierno', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505C', 'Pago a no residentes – Intereses de créditos de organismos multilaterales', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505D', 'Pago a no residentes - Intereses por financiamiento de proveedores externos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505E', 'Pago a no residentes - Intereses de otros créditos externos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '505F', 'Pago a no residentes - Otros Intereses y Rendimientos Financieros', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '509', 'Pago a no residentes- Cánones, derechos de autor,  marcas, patentes y similares', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '509A', 'Pago a no residentes - Regalías por concepto de franquicias', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '510', 'Pago a no residentes - Otras ganancias de capital distintas de enajenación de derechos representativos de capital ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '511', 'Pago a no residentes - Servicios profesionales independientes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '512', 'Pago a no residentes - Servicios profesionales dependientes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '513A', 'Pago a no residentes - Deportistas', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '514', 'Pago a no residentes - Participación de consejeros', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '515', 'Pago a no residentes- Artistas y relacionados a  organización, producción y espectáculos artísticos y culturales en Ecuador ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '516', 'Pago a no residentes - Pensiones', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '517', 'Pago a no residentes- Reembolso de Gastos', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '518', 'Pago a no residentes- Funciones Públicas', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '519', 'Pago a no residentes - Estudiantes', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520A', 'Pago a no residentes - Pago a proveedores de servicios hoteleros y turísticos en el exterior', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520B', 'Pago a no residentes - Arrendamientos mercantil internacional', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520D', 'Pago a no residentes - Comisiones por exportaciones y por promoción de turismo receptivo', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520E', 'Pago a no residentes - Por las empresas de transporte marítimo o aéreo y por empresas pesqueras de alta mar, por su actividad.', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520F', 'Pago a no residentes - Por las agencias internacionales de prensa', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '520G', 'Pago a no residentes - Contratos de fletamento de naves para empresas de transporte aéreo o marítimo internacional', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '521', 'Pago a no residentes - Enajenación de derechos representativos de capital u otros derechos que permitan la exploración, explotación, concesión o similares de sociedades', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '523A', 'Pago a no residentes - Seguros y reaseguros (primas y cesiones)  ', 0),
(nextval('tb_retenciones_codigos_id_seq'),  false, '1', '525', 'Pago a no residentes- Donaciones en dinero -Impuesto a las donaciones', 0);
