
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('16', 'AMERICAN SAMOA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('52', 'PRINCIPADO DEL VALLE DE ANDORRA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('74', 'BOUVET ISLAND', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('101', 'ARGENTINA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('102', 'BOLIVIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('103', 'BRASIL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('104', 'CANADA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('105', 'COLOMBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('106', 'COSTA RICA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('107', 'CUBA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('108', 'CHILE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('109', 'ANGUILA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('110', 'ESTADOS UNIDOS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('111', 'GUATEMALA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('112', 'HAITI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('113', 'HONDURAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('114', 'JAMAICA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('115', 'MALVINAS ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('116', 'MEXICO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('117', 'NICARAGUA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('118', 'PANAMA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('119', 'PARAGUAY', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('120', 'PERU', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('121', 'PUERTO RICO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('122', 'REPUBLICA DOMINICANA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('123', 'EL SALVADOR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('124', 'TRINIDAD Y TOBAGO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('125', 'URUGUAY', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('126', 'VENEZUELA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('127', 'CURAZAO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('129', 'BAHAMAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('130', 'BARBADOS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('131', 'GRANADA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('132', 'GUYANA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('133', 'SURINAM', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('134', 'ANTIGUA Y BARBUDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('135', 'BELICE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('136', 'DOMINICA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('137', 'SAN CRISTOBAL Y NEVIS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('138', 'SANTA LUCIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('139', 'SAN VICENTE Y LAS GRANAD.', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('140', 'ANTILLAS HOLANDESAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('141', 'ARUBA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('142', 'BERMUDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('143', 'GUADALUPE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('144', 'GUYANA FRANCESA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('145', 'ISLAS CAIMAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('146', 'ISLAS VIRGENES (BRITANICAS)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('147', 'JOHNSTON ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('148', 'MARTINICA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('149', 'MONTSERRAT ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('151', 'TURCAS Y CAICOS ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('152', 'VIRGENES,ISLAS(NORT.AMER.)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('201', 'ALBANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('202', 'ALEMANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('203', 'AUSTRIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('204', 'BELGICA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('205', 'BULGARIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('207', 'ALBORAN Y PEREJIL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('208', 'DINAMARCA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('209', 'ESPAÑA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('211', 'FRANCIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('212', 'FINLANDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('213', 'REINO UNIDO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('214', 'GRECIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('215', 'PAISES BAJOS (HOLANDA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('216', 'HUNGRIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('217', 'IRLANDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('218', 'ISLANDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('219', 'ITALIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('220', 'LUXEMBURGO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('221', 'MALTA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('222', 'NORUEGA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('223', 'POLONIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('224', 'PORTUGAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('225', 'RUMANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('226', 'SUECIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('227', 'SUIZA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('228', 'CANARIAS ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('229', 'UCRANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('230', 'RUSIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('231', 'YUGOSLAVIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('233', 'ANDORRA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('234', 'LIECHTENSTEIN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('235', 'MONACO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('237', 'SAN MARINO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('238', 'VATICANO (SANTA SEDE)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('239', 'GIBRALTAR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('241', 'BELARUS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('242', 'BOSNIA Y HERZEGOVINA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('243', 'CROACIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('244', 'ESLOVENIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('245', 'ESTONIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('246', 'GEORGIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('247', 'GROENLANDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('248', 'LETONIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('249', 'LITUANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('250', 'MOLDOVA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('251', 'MACEDONIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('252', 'ESLOVAQUIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('253', 'ISLAS FAROE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('260', 'FRENCH SOUTHERN TERRITORIES', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('301', 'AFGANISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('302', 'ARABIA SAUDITA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('303', 'MYANMAR (BURMA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('304', 'CAMBOYA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('306', 'COREA NORTE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('307', 'TAIWAN (CHINA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('308', 'FILIPINAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('309', 'INDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('310', 'INDONESIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('311', 'IRAK', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('312', 'IRAN (REPUBLICA ISLAMICA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('313', 'ISRAEL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('314', 'JAPON', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('315', 'JORDANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('316', 'KUWAIT', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('317', 'LAOS, REP. POP. DEMOC.', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('318', 'LIBANO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('319', 'MALASIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('321', 'MONGOLIA (MANCHURIA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('322', 'PAKISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('323', 'SIRIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('325', 'TAILANDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('327', 'BAHREIN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('328', 'BANGLADESH', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('329', 'BUTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('330', 'COREA DEL SUR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('331', 'CHINA POPULAR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('332', 'CHIPRE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('333', 'EMIRATOS ARABES UNIDOS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('334', 'QATAR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('335', 'MALDIVAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('336', 'NEPAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('337', 'OMAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('338', 'SINGAPUR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('339', 'SRI LANKA (CEILAN)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('341', 'VIETNAM', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('342', 'YEMEN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('343', 'ISLAS HEARD Y MCDONALD', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('344', 'BRUNEI DARUSSALAM', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('346', 'TURQUIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('347', 'AZERBAIJAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('348', 'KAZAJSTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('349', 'KIRGUIZISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('350', 'TAJIKISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('351', 'TURKMENISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('352', 'UZBEKISTAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('353', 'PALESTINA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('354', 'HONG KONG', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('355', 'MACAO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('356', 'ARMENIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('382', 'MONTENEGRO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('402', 'BURKINA FASO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('403', 'ARGELIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('404', 'BURUNDI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('405', 'CAMERUN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('406', 'CONGO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('407', 'ETIOPIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('408', 'GAMBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('409', 'GUINEA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('410', 'LIBERIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('412', 'MADAGASCAR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('413', 'MALAWI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('414', 'MALI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('415', 'MARRUECOS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('416', 'MAURITANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('417', 'NIGERIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('419', 'ZIMBABWE (RHODESIA)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('420', 'SENEGAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('421', 'SUDAN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('422', 'SUDAFRICA (CISKEI)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('423', 'SIERRA LEONA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('425', 'TANZANIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('426', 'UGANDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('427', 'ZAMBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('428', 'ÅLAND ISLANDS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('429', 'BENIN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('430', 'BOTSWANA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('431', 'REPUBLICA CENTROAFRICANA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('432', 'COSTA DE MARFIL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('433', 'CHAD', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('434', 'EGIPTO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('435', 'GABON', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('436', 'GHANA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('437', 'GUINEA-BISSAU', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('438', 'GUINEA ECUATORIAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('439', 'KENIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('440', 'LESOTHO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('441', 'MAURICIO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('442', 'MOZAMBIQUE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('443', 'MAYOTTE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('444', 'NIGER', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('445', 'RWANDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('446', 'SEYCHELLES', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('447', 'SAHARA OCCIDENTAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('448', 'SOMALIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('449', 'SANTO TOME Y PRINCIPE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('450', 'SWAZILANDIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('451', 'TOGO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('452', 'TUNEZ', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('453', 'ZAIRE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('454', 'ANGOLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('456', 'CABO VERDE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('458', 'COMORAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('459', 'DJIBOUTI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('460', 'NAMIBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('463', 'ERITREA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('464', 'MOROCCO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('465', 'REUNION', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('466', 'SANTA ELENA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('499', 'JERSEY', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('501', 'AUSTRALIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('503', 'NUEVA ZELANDA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('504', 'SAMOA OCCIDENTAL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('506', 'FIJI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('507', 'PAPUA NUEVA GUINEA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('508', 'TONGA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('509', 'PALAO (BELAU) ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('510', 'KIRIBATI', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('511', 'MARSHALL ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('512', 'MICRONESIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('513', 'NAURU', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('514', 'SALOMON ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('515', 'TUVALU', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('516', 'VANUATU', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('517', 'GUAM', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('518', 'ISLAS COCOS (KEELING)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('519', 'ISLAS COOK', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('520', 'ISLAS NAVIDAD', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('521', 'MIDWAY ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('522', 'NIUE ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('523', 'NORFOLK ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('524', 'NUEVA CALEDONIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('525', 'PITCAIRN, ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('526', 'POLINESIA FRANCESA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('529', 'TIMOR DEL ESTE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('530', 'Tokelau', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('531', 'WAKE ISLA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('532', 'WALLIS Y FUTUNA, ISLAS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('534', 'SINT MAARTEN (DUTCH PART)', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('590', 'SAINT BARTHELEMY', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('593', 'ECUADOR', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('594', 'AGUAS INTERNACIONALES', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('595', 'ALTO VOLTA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('596', 'BIELORRUSIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('597', 'COTE DIVOIRE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('598', 'CYPRUS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('599', 'REPUBLICA CHECA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('600', 'FALKLAND ISLANDS', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('601', 'LATVIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('602', 'LIBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('603', 'NORTHERN MARIANA ISL', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('604', 'ST. PIERRE AND MIQUE', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('605', 'SYRIAN ARAB REPUBLIC', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('606', 'TERRITORIO ANTARTICO BRITANICO', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('607', 'TERRITORIO BRITANICO OCEANO IN', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('688', 'SERBIA', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('831', 'GUERNSEY', false);
INSERT INTO public.tb_paises (codigo_pais, pais, deleted) VALUES('833', 'ISLE OF MAN', false);

-- Script generado desde Paises.xlsx - TABLA 17: PARAÍSOS FISCALES
-- Tabla: public.tb_paraisos_fiscales

INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('1', false, 'ANGUILA (Territorio no autónomo del Reino Unido)', '109');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('2', false, 'ANTIGUA Y BARBUDA (Estado independiente)', '134');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('3', false, 'ARCHIPIÉLAGO DE SVALBARD', '222');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('4', false, 'ARUBA', '141');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('5', false, 'BARBADOS (Estado independiente)', '130');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('6', false, 'BELICE (Estado independiente)', '135');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('7', false, 'BERMUDAS (Territorio no autónomo del Reino Unido)', '142');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('8', false, 'BONAIRE, SABA Y SAN EUSTAQUIO', '215');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('9', false, 'BRUNEI DARUSSALAM (Estado independiente)', '344');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('10', false, 'CAMPIONE D''ITALIA (Comune di Campioned''Italia)', '219');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('11', false, 'COLONIA DE GIBRALTAR', '239');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('12', false, 'COMUNIDAD DE LAS BAHAMAS (Estado independiente)', '129');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('13', false, 'CURAZAO', '127');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('14', false, 'ESTADO ASOCIADO DE GRANADA (Estado independiente)', '131');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('15', false, 'ESTADO DE BAHREIN (Estado independiente)', '327');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('16', false, 'ESTADO DE KUWAIT (Estado independiente)', '316');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('17', false, 'ESTADO LIBRE ASOCIADO DE PUERTO RICO (Estado asociado a los EEUU)', '121');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('18', false, 'EMIRATOS ÁRABES UNIDOS (Estado independiente)', '333');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('19', false, 'FEDERACIÓN DE SAN CRISTÓBAL (Islas Saint Kitts and Nevis: independientes)', '137');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('20', false, 'GRAN DUCADO DE LUXEMBURGO', '220');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('21', false, 'GROENLANDIA', '247');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('22', false, 'GUAM (Territorio no autónomo de los EEUU)', '517');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('23', false, 'ISLA DE ASCENSIÓN', '466');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('24', false, 'ISLAS AZORES', '224');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('25', false, 'ISLAS CAIMÁN (Territorio no autónomo del Reino Unido)', '145');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('26', false, 'ISLAS CHRISTMAS', '520');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('27', false, 'ISLA DE COCOS O KEELING', '518');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('28', false, 'ISLA DE COOK (Territorio autónomo asociado a Nueva Zelanda)', '519');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('29', false, 'ISLA DE MAN (Territorio del Reino Unido)', '833');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('30', false, 'ISLA DE NORFOLK', '523');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('31', false, 'ISLA DE SAN PEDRO Y MIGUELÓN', '604');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('32', false, 'ISLAS DEL CANAL (Guernesey, Alderney, Isla de Great Stark, Herm, Little Sark, Brechou, Jethou, Lihou)', '831');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('33', false, 'ISLA QESHM', '312');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('34', false, 'ISLAS SALOMÓN', '514');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('35', false, 'ISLAS TURKAS E ISLAS CAICOS (Territorio no autónomo del Reino Unido)', '151');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('36', false, 'ISLAS VÍRGENES BRITÁNICAS (Territorio no autónomo del Reino Unido)', '146');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('37', false, 'ISLAS VÍRGENES DE ESTADOS UNIDOS DE AMÉRICA', '152');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('38', false, 'KIRIBATI', '510');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('39', false, 'LABUAN', '319');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('40', false, 'MACAO', '355');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('41', false, 'MADEIRA (Territorio de Portugal)', '224');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('42', false, 'MANCOMUNIDAD DE DOMINICA (Estado asociado)', '136');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('43', false, 'MONTSERRAT (Territorio no autónomo del Reino Unido)', '149');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('44', false, 'MYANMAR (ex Birmania)', '303');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('45', false, 'NIGERIA', '417');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('46', false, 'NIUE', '522');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('47', false, 'PALAU', '509');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('48', false, 'PITCAIRN', '525');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('49', false, 'POLINESIA FRANCESA (Territorio de Ultramar de Francia)', '260');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('50', false, 'PRINCIPADO DE LIECHTENSTEIN (Estado independiente)', '234');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('51', false, 'PRINCIPADO DE MÓNACO', '235');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('52', false, 'PRINCIPADO DEL VALLE DE ANDORRA', '233');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('53', false, 'REINO DE SWAZILANDIA (Estado independiente)', '450');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('54', false, 'REINO DE TONGA (Estado independiente)', '508');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('55', false, 'REINO HACHEMITA DE JORDANIA', '315');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('56', false, 'REPÚBLICA COOPERATIVA DE GUYANA (Estado independiente)', '132');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('57', false, 'REPÚBLICA DE ALBANIA', '201');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('58', false, 'REPÚBLICA DE ANGOLA', '454');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('59', false, 'REPÚBLICA DE CABO VERDE (Estado independiente)', '456');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('60', false, 'REPÚBLICA DE CHIPRE', '332');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('61', false, 'REPÚBLICA DE DJIBOUTI (Estado independiente)', '459');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('62', false, 'REPÚBLICA DE LAS ISLAS MARSHALL (Estado independiente)', '511');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('63', false, 'REPÚBLICA DE LIBERIA (Estado independiente)', '410');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('64', false, 'REPÚBLICA DE MALDIVAS (Estado independiente)', '335');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('65', false, 'REPÚBLICA DE MALTA (Estado independiente)', '221');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('66', false, 'REPÚBLICA DE MAURICIO', '441');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('67', false, 'REPÚBLICA DE NAURU (Estado independiente)', '513');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('68', false, 'REPÚBLICA DE PANAMÁ (Estado independiente)', '118');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('69', false, 'REPÚBLICA DE SEYCHELLES (Estado independiente)', '446');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('70', false, 'REPÚBLICA DE TRINIDAD Y TOBAGO', '124');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('71', false, 'REPÚBLICA DE TÚNEZ', '452');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('72', false, 'REPÚBLICA DE VANUATU', '516');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('73', false, 'REPÚBLICA DEL YEMEN', '342');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('74', false, 'REPÚBLICA DEMOCRÁTICA SOCIALISTA DE SRI LANKA', '339');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('75', false, 'SAMOA AMERICANA (Territorio no autónomo de los EEUU)', '16');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('76', false, 'SAMOA OCCIDENTAL', '504');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('77', false, 'SAN VICENTE Y LAS GRANADINAS (Estado independiente)', '139');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('78', false, 'SANTA ELENA', '466');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('79', false, 'SANTA LUCÍA', '138');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('80', false, 'SAN MARTÍN', '534');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('81', false, 'SERENÍSIMA REPÚBLICA DE SAN MARINO (Estado independiente)', '237');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('82', false, 'SULTANADO DE OMAN', '337');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('83', false, 'TOKELAU', '530');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('84', false, 'TRISTAN DA CUNHA (SH Saint Helena)', '466');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('85', false, 'TUVALU', '515');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('86', false, 'ZONA LIBRE DE OSTRAVA', '599');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('88', false, 'ISLAS DEL CANAL (Jersey)', '499');
INSERT INTO public.tb_paraisos_fiscales (codigo, deleted, paraiso_fiscal, codigo_pais) VALUES('89', false, 'HONG KONG', '354');
