package com.calero.lili.core.modAdModulos.builder;

import com.calero.lili.core.modAdModulos.AdModulosEntity;
import com.calero.lili.core.modAdModulos.dto.AdModuloRequestDto;
import com.calero.lili.core.modAdModulos.dto.AdModuloResponseDto;
import org.springframework.stereotype.Component;

@Component
public class AdModuloBuilder {

    public AdModulosEntity builderEntity(AdModuloRequestDto model) {
        return AdModulosEntity.builder()
                .idModAdminEmpresas(model.getIdModAdminEmpresas())
                .idModAdminEmpresasSeries(model.getIdModAdminEmpresasSeries())
                .idModAdminEmpresasSeriesDocumentos(model.getIdModAdminEmpresasSeriesDocumentos())
                .idModAdminEmpresasSucursales(model.getIdModAdminEmpresasSucursales())
                .idModAdminListaNegra(model.getIdModAdminListaNegra())
                .idModAdminPorcentajes(model.getIdModAdminPorcentajes())
                .idModCargarExcelServices(model.getIdModCargarExcelServices())
                .idModCargarExcelDP(model.getIdModCargarExcelDP())
                .idModClientesConfiguraciones(model.getIdModClientesConfiguraciones())
                .idModClientesTickets(model.getIdModClientesTickets())
                .idModCompras(model.getIdModCompras())
                .idModComprasItems(model.getIdModComprasItems())
                .idModComprasItemsBodegas(model.getIdModComprasItemsBodegas())
                .idModComprasItemsCategorias(model.getIdModComprasItemsCategorias())
                .idModComprasItemsGrupos(model.getIdModComprasItemsGrupos())
                .idModComprasItemsImpuesto(model.getIdModComprasItemsImpuesto())
                .idModComprasItemsMarcas(model.getIdModComprasItemsMarcas())
                .idModComprasItemsMedidas(model.getIdModComprasItemsMedidas())
                .idModComprasOrden(model.getIdModComprasOrden())
                .idModComprasProveedoresGrupos(model.getIdModComprasProveedoresGrupos())
                .idModContabilidad(model.getIdModContabilidad())
                .idModImpuestosAnexos(model.getIdModImpuestosAnexos())
                .idModImpuestosProcesos(model.getIdModImpuestosProcesos())
                .idModLocalidades(model.getIdModLocalidades())
                .idModModuloDatas(model.getIdModModuloDatas())
                .idModRRHH(model.getIdModRRHH())
                .idModTerceros(model.getIdModTerceros())
                .idModTercerosClientesParametros(model.getIdModTercerosClientesParametros())
                .idModTercerosProvedoresParametros(model.getIdModTercerosProvedoresParametros())
                .idModTesoreria(model.getIdModTesoreria())
                .idModVentas(model.getIdModVentas())
                .idModVentasClientesGrupos(model.getIdModVentasClientesGrupos())
                .idModVentasCotizaciones(model.getIdModVentasCotizaciones())
                .idModVentasGuias(model.getIdModVentasGuias())
                .idModVentasPedidos(model.getIdModVentasPedidos())
                .idModVentasRetenciones(model.getIdModVentasRetenciones())
                .idModVentasVendedores(model.getIdModVentasVendedores())
                .idModVentasZonas(model.getIdModVentasZonas())
                .build();
    }

    public AdModulosEntity builderUpdateEntity(AdModuloRequestDto model, AdModulosEntity item) {
        return AdModulosEntity.builder()
                .idModulo(item.getIdModulo())
                .idModAdminEmpresas(model.getIdModAdminEmpresas())
                .idModAdminEmpresasSeries(model.getIdModAdminEmpresasSeries())
                .idModAdminEmpresasSeriesDocumentos(model.getIdModAdminEmpresasSeriesDocumentos())
                .idModAdminEmpresasSucursales(model.getIdModAdminEmpresasSucursales())
                .idModAdminListaNegra(model.getIdModAdminListaNegra())
                .idModAdminPorcentajes(model.getIdModAdminPorcentajes())
                .idModCargarExcelServices(model.getIdModCargarExcelServices())
                .idModCargarExcelDP(model.getIdModCargarExcelDP())
                .idModClientesConfiguraciones(model.getIdModClientesConfiguraciones())
                .idModClientesTickets(model.getIdModClientesTickets())
                .idModCompras(model.getIdModCompras())
                .idModComprasItems(model.getIdModComprasItems())
                .idModComprasItemsBodegas(model.getIdModComprasItemsBodegas())
                .idModComprasItemsCategorias(model.getIdModComprasItemsCategorias())
                .idModComprasItemsGrupos(model.getIdModComprasItemsGrupos())
                .idModComprasItemsImpuesto(model.getIdModComprasItemsImpuesto())
                .idModComprasItemsMarcas(model.getIdModComprasItemsMarcas())
                .idModComprasItemsMedidas(model.getIdModComprasItemsMedidas())
                .idModComprasOrden(model.getIdModComprasOrden())
                .idModComprasProveedoresGrupos(model.getIdModComprasProveedoresGrupos())
                .idModContabilidad(model.getIdModContabilidad())
                .idModImpuestosAnexos(model.getIdModImpuestosAnexos())
                .idModImpuestosProcesos(model.getIdModImpuestosProcesos())
                .idModLocalidades(model.getIdModLocalidades())
                .idModModuloDatas(model.getIdModModuloDatas())
                .idModRRHH(model.getIdModRRHH())
                .idModTerceros(model.getIdModTerceros())
                .idModTercerosClientesParametros(model.getIdModTercerosClientesParametros())
                .idModTercerosProvedoresParametros(model.getIdModTercerosProvedoresParametros())
                .idModTesoreria(model.getIdModTesoreria())
                .idModVentas(model.getIdModVentas())
                .idModVentasClientesGrupos(model.getIdModVentasClientesGrupos())
                .idModVentasCotizaciones(model.getIdModVentasCotizaciones())
                .idModVentasGuias(model.getIdModVentasGuias())
                .idModVentasPedidos(model.getIdModVentasPedidos())
                .idModVentasRetenciones(model.getIdModVentasRetenciones())
                .idModVentasVendedores(model.getIdModVentasVendedores())
                .idModVentasZonas(model.getIdModVentasZonas())
                .build();
    }

    public AdModuloResponseDto builderResponse(AdModulosEntity model) {
        return AdModuloResponseDto.builder()
                .idModuloData(model.getIdModulo())
                .idModAdminEmpresas(model.getIdModAdminEmpresas())
                .idModAdminEmpresasSeries(model.getIdModAdminEmpresasSeries())
                .idModAdminEmpresasSeriesDocumentos(model.getIdModAdminEmpresasSeriesDocumentos())
                .idModAdminEmpresasSucursales(model.getIdModAdminEmpresasSucursales())
                .idModAdminListaNegra(model.getIdModAdminListaNegra())
                .idModAdminPorcentajes(model.getIdModAdminPorcentajes())
                .idModCargarExcelServices(model.getIdModCargarExcelServices())
                .idModCargarExcelDP(model.getIdModCargarExcelDP())
                .idModClientesConfiguraciones(model.getIdModClientesConfiguraciones())
                .idModClientesTickets(model.getIdModClientesTickets())
                .idModCompras(model.getIdModCompras())
                .idModComprasItems(model.getIdModComprasItems())
                .idModComprasItemsBodegas(model.getIdModComprasItemsBodegas())
                .idModComprasItemsCategorias(model.getIdModComprasItemsCategorias())
                .idModComprasItemsGrupos(model.getIdModComprasItemsGrupos())
                .idModComprasItemsImpuesto(model.getIdModComprasItemsImpuesto())
                .idModComprasItemsMarcas(model.getIdModComprasItemsMarcas())
                .idModComprasItemsMedidas(model.getIdModComprasItemsMedidas())
                .idModComprasOrden(model.getIdModComprasOrden())
                .idModComprasProveedoresGrupos(model.getIdModComprasProveedoresGrupos())
                .idModContabilidad(model.getIdModContabilidad())
                .idModImpuestosAnexos(model.getIdModImpuestosAnexos())
                .idModImpuestosProcesos(model.getIdModImpuestosProcesos())
                .idModLocalidades(model.getIdModLocalidades())
                .idModModuloDatas(model.getIdModModuloDatas())
                .idModRRHH(model.getIdModRRHH())
                .idModTerceros(model.getIdModTerceros())
                .idModTercerosClientesParametros(model.getIdModTercerosClientesParametros())
                .idModTercerosProvedoresParametros(model.getIdModTercerosProvedoresParametros())
                .idModTesoreria(model.getIdModTesoreria())
                .idModVentas(model.getIdModVentas())
                .idModVentasClientesGrupos(model.getIdModVentasClientesGrupos())
                .idModVentasCotizaciones(model.getIdModVentasCotizaciones())
                .idModVentasGuias(model.getIdModVentasGuias())
                .idModVentasPedidos(model.getIdModVentasPedidos())
                .idModVentasRetenciones(model.getIdModVentasRetenciones())
                .idModVentasVendedores(model.getIdModVentasVendedores())
                .idModVentasZonas(model.getIdModVentasZonas())
                .build();
    }
}
